name: Daily Saying
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - uses: ./
